# This file was generated by GoReleaser. DO NOT EDIT.
cask "ethsy-connect" do
  name "ethsy-connect"
  desc "CLI client for ethsy.me remote tmux session sharing"
  homepage "https://github.com/devsigner9920/ethsy-ssh"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ethsy-connect"

  on_macos do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_darwin_amd64.tar.gz"
      sha256 "ddbba33622e2c7bcbeec17ebb005e5a7f828678dc1d7ef24571040ae0e0496d6"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_darwin_arm64.tar.gz"
      sha256 "2fe96094a7219d8b22fa011254eddcaab8750a9362505142c6097a566c158808"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_linux_amd64.tar.gz"
      sha256 "776adc050562e5536b49f38553413ed40a819a5bed4d23d0926a2fd0f2747187"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_linux_arm64.tar.gz"
      sha256 "51882d87559e6a457a150ff0f0ecae105af5713f82820d02608ec03c9cc3e49d"
    end
  end

  # No zap stanza required
end
