# This file was generated by GoReleaser. DO NOT EDIT.
cask "ethsy-server" do
  name "ethsy-server"
  desc "Server for ethsy.me remote tmux session sharing"
  homepage "https://github.com/devsigner9920/ethsy-ssh"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ethsy-server"

  on_macos do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_darwin_amd64.tar.gz"
      sha256 "6c951b5c5a3040731f78364678f49faff27752cadeb1d5b020add01955b8cfa6"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_darwin_arm64.tar.gz"
      sha256 "2c816aa59d254cb7c689a6abc1c4b0382581ee087ada293769851442232083eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_linux_amd64.tar.gz"
      sha256 "79d612417ea4ecfacfcca6db2fa9255c7d975373d5271cba653a5478c80afc4c"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_linux_arm64.tar.gz"
      sha256 "36b97f321cb177577382d186dcfe3f7daa63d4e8f640d4ab5f8461834aab3f1e"
    end
  end

  # No zap stanza required
end
