# This file was generated by GoReleaser. DO NOT EDIT.
cask "ethsy-connect" do
  name "ethsy-connect"
  desc "CLI client for ethsy.me remote tmux session sharing"
  homepage "https://github.com/devsigner9920/ethsy-ssh"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ethsy"

  on_macos do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_darwin_amd64.tar.gz"
      sha256 "02d3a29bef51284380886b828bd2b8c9930e16a1f15a15b03911edf888ccd5f6"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_darwin_arm64.tar.gz"
      sha256 "315af30ab0e34b88621890647844d69632f440e69be069a84f316a2d22d5e148"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_linux_amd64.tar.gz"
      sha256 "5c6a194cddb1d3c00ff18b5c8bd16cd30d94176b8f0aff9ed34b64fd029476f6"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-connect_linux_arm64.tar.gz"
      sha256 "a505288f5885ab03d4b723431e09e9f617707bb7877b1449811949a412da58bd"
    end
  end

  # No zap stanza required
end
