# This file was generated by GoReleaser. DO NOT EDIT.
cask "ethsy-server" do
  name "ethsy-server"
  desc "Server for ethsy.me remote tmux session sharing"
  homepage "https://github.com/devsigner9920/ethsy-ssh"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ethsy-server"

  on_macos do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_darwin_amd64.tar.gz"
      sha256 "6ac140402a184aee027a31f85107897f4f67961086c7750021718100b91ff36d"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_darwin_arm64.tar.gz"
      sha256 "d2ed093ecbcd75a78ee2038145a927e4d2857149b973509a13d2d2e819be122b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_linux_amd64.tar.gz"
      sha256 "14178d545c9f1ca27ac9b696b9caea9aa828d5e25e6d296d3b9d56afb5c79ecd"
    end
    on_arm do
      url "https://github.com/devsigner9920/ethsy-ssh/releases/download/v#{version}/ethsy-server_linux_arm64.tar.gz"
      sha256 "3b8cdbcfe1f1c3cb1677c4cac5e81a9a5152c09234221e24359e90636933227f"
    end
  end

  # No zap stanza required
end
